name: TER release

on:
  push:
    tags:
      - '*'

jobs:
  assets:
    name: build node dependencies
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Resources/Private/Assets
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'Resources/Private/Assets/package-lock.json'
      - run: npm install
      - run: npm run build
      - name: Upload assets
        uses: actions/upload-artifact@v4
        with:
          name: assets
          path: Resources/Public

  ter-release:
    name: TER release
    needs: assets
    runs-on: ubuntu-latest
    env:
      TYPO3_EXTENSION_KEY: 'ausstello'
      REPOSITORY_URL: 'https://github.com/werkraum/ausstello'
      TYPO3_API_TOKEN: ${{ secrets.TYPO3_API_TOKEN }}
      TYPO3_API_USERNAME: ${{ secrets.TYPO3_API_USERNAME }}
      TYPO3_API_PASSWORD: ${{ secrets.TYPO3_API_PASSWORD }}

    steps:
      - name: Download built assets
        uses: actions/download-artifact@v4
        with:
          name: assets

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: intl, mbstring, xml, soap, zip, curl

      - name: Install EXT:tailor
        run: composer global require typo3/tailor --prefer-dist --no-progress --no-suggest

      - name: Display contents
        run: ls -la ${{ github.workspace }}

      - name: Upload EXT:${{ env.EXTENSION_KEY }} as ${{ steps.get_version.outputs.VERSION }} to TER
        run: php ~/.composer/vendor/bin/tailor ter:publish --path="${{ github.workspace }}/../" --comment="New release of version ${{ steps.get_version.outputs.VERSION }} - see details, changelog and documentation on ${{ env.REPOSITORY_URL }}" ${{ steps.get_version.outputs.VERSION }}
