name: TER release

on:
  push:
    tags:
      - '*'

jobs:
#  assets:
#    name: build node dependencies
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#      - uses: actions/setup-node@v4
#        with:
#          node-version: '20'
#          cache: 'npm'
#          cache-dependency-path: 'Build/package-lock.json'
#      - run: npm install
#        working-directory: Build
#      - run: npm run build
#        working-directory: Build
#      - name: Upload assets
#        uses: actions/upload-artifact@v4
#        with:
#          name: assets
#          path: Resources/Public

  ter-release:
    name: TER release
#    needs: assets
    runs-on: ubuntu-latest
    env:
      TYPO3_EXTENSION_KEY: 'ausstello'
      REPOSITORY_URL: 'https://github.com/werkraum/ausstello'
      TYPO3_API_TOKEN: ${{ secrets.TYPO3_API_TOKEN }}
      TYPO3_API_USERNAME: ${{ secrets.TYPO3_API_USERNAME }}
      TYPO3_API_PASSWORD: ${{ secrets.TYPO3_API_PASSWORD }}

    steps:
      - uses: actions/checkout@v4

#      - name: Download built assets
#        uses: actions/download-artifact@v4
#        with:
#          name: assets
#          path: Resources/Public

      - name: Get version
        id: get-version
        run: echo "version=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          extensions: intl, mbstring, json, zip, curl
          tools: composer:v2

      - name: Install EXT:tailor
        run: composer global require typo3/tailor --prefer-dist --no-progress --no-suggest

      - name: Display Contents
        run: ls -la ${{ github.workspace }}

      - name: Upload EXT:${{ env.EXTENSION_KEY }} as ${{ env.version }} to TER
        run: php ~/.composer/vendor/bin/tailor ter:publish --path="${{ github.workspace }}" --comment="New release of version ${{ env.version }} - see details, changelog and documentation on ${{ env.REPOSITORY_URL }}" ${{ env.version }}
